### ISSUE TITLE
How to connect to serial interface of Roland DXY-1150?

### ISSUE THREAD

**Issue by OrangeTux** [playduck/plotter-utils#1]
I recently bought a Roland DXY-1150 and I'd like to control it myself. Unfortunately, I can't get it working using [this RS 232 cable](https://www.amazon.de/-/en/dp/B001UHCHMG?psc=1&ref=ppx_yo2ov_dt_b_product_details) I bought.

Here's a snippet that should toggle the pen using the RD-GL I instructions PD and PU

![image](https://user-images.githubusercontent.com/1565144/216771351-87f68a83-688e-4127-8e83-2e5db6c6f375.png)
---
![image](https://user-images.githubusercontent.com/1565144/216771364-aeb01321-5d97-4dd0-ad9b-c27a4a85d0c9.png)

```python
import time
import serial

with serial.Serial(
    port="/dev/ttyUSB0",
    baudrate=9600,
    bytesize=serial.SEVENBITS,
    parity=serial.PARITY_EVEN,
    stopbits=serial.STOPBITS_ONE,
    rtscts=True,
    timeout=3
) as ser:
    # Pen Down
    ser.write(b"PD;")
    time.sleep(1)
     
    # Pen Up
    ser.write(b"PU;")
```

Dip switch 2-8, 2-9 and 2-10 control the serial settings. 2-10 and 2-9 are off and 2-8 is on.

![image](https://user-images.githubusercontent.com/1565144/216771467-5a153255-422c-4b27-a491-992da2d62666.png)

I'm wondering whether I bought the right cable. The data sheet states the device communicates over RS-232C. The [Internet teaches me that RS-232C is the same as RS-232](https://electronics.stackexchange.com/questions/382210/what-is-the-difference-between-rs-232-and-rs-232-c). However, the readme of this project indicate otherwise: 
> The Plotter uses the [RS-232-C](https://github.com/playduck/plotter-utils/blob/main/datasheets/EIA_RS-232-C.pdf) implementation. This requires much greater voltage levels than modern transmitters are capable of producing.

Do I have the wrong cable? Do you've any suggestions?

**Comment by playduck** [comment]
Something to try first would be using standard [8N1](https://en.wikipedia.org/wiki/8-N-1):
8 Data bits, No Parity, 1 Stop Bit (you can do this by simply omitting the `bytesize`, `parity` and `stopbits` options).
Also worth a shot is trying it with `rtscts=False`, just in case that's causing any problems.

The modern standard for RS-232 is described by TIA-232-F. The actual protocol is identical to the original RS-232-C version from 1969. However, the voltage levels did change. Matter of fact, the SO question you linked mentions this in [the second reply below](https://electronics.stackexchange.com/a/382215) ;).
On paper they should be compatible, but who knows what the cables really implement.

I can't tell you what version of the standard your cable implements or what driver IC it uses.
The cable could likely be the problem. Only way to verify for sure is by looking at the cable's output with an oscilloscope. The cable I initially used looked very similar to yours and it didn't work.

I solved this by frankensteining an adapter:
![Image](https://user-images.githubusercontent.com/24953726/216781779-39cd03d4-ccaa-4837-abae-a722477391a3.jpeg)

It's not perfect, but it gets the job (mostly) done.
It consists of:

- DB25 to DB9 Adapter to interface with the plotters DB25 port
- [DB9 Male to Male Gender Changer](https://www.amazon.de/gp/product/B00BN6VQ4Y/ref=ppx_yo_dt_b_asin_title_o08_s00?ie=UTF8&psc=1)
- [MAX3232 Transceiver](https://www.amazon.de/gp/product/B07DK3874B/ref=ppx_yo_dt_b_asin_title_o03_s00?ie=UTF8&psc=1)
- USB to UART Bridge (I don't have the link anymore, any random converter will do, mine uses the PL2303 IC in 5V mode)

This monstrosity actually works. I can use it to send HPGL to the plotter.
Only downside: 
The RTS and CTS signals are not transmitted. This means, if you send too much data at once, the plotters buffer can overflow, potentially ruining the plot.
A simple hack to overcome this is to simply send data slower by just waiting a bit for each command.
That's not perfect but it works. (This can be done with the python `inter_byte_timeout` option)

The real solution would be to build a device capable of both translating Tx and Rx as well as CTS and RTS.
I think the [repo already includes a KiCad board](https://github.com/playduck/plotter-utils/tree/main/KiCad/plotterUSBInterface) for this purpose (Designed by @SenpaiSimon).
We never gotten around to building and testing it though.

**Comment by OrangeTux** [comment]
Many thanks for the response! Unfortunately, changing serial settings didn't work. So I've to build a Frankenstein connector. 

Thanks again!

**Comment by OrangeTux** [comment]
I works! Many thanks for your help. I bought the hardware and also had to set `rtscts` to `False`. For anyone else stumbling at this issue in the future, here is my code. `SP2` instructs the plotter to select pen in slot 2. Followed by `SP1` which selects the first pen.

```python
import time

import serial

with serial.Serial(
    port="/dev/ttyUSB0",
    baudrate=9600,
    bytesize=serial.SEVENBITS,
    parity=serial.PARITY_EVEN,
    stopbits=serial.STOPBITS_ONE,
    rtscts=False,
    timeout=1,
) as ser:
    ser.write(b"SP2;")
    time.sleep(1)
    ser.write(b"SP1;")
```
